#drivers/input/touchscreen/focaltech_touch/focaltech_test
#
#Makefile for test module
#



obj-$(CONFIG_TOUCHSCREEN_FOCAL_FT8719_E7T) += focaltech_test.o
obj-$(CONFIG_TOUCHSCREEN_FOCAL_FT8719_E7T) += focaltech_test_ini.o
obj-$(CONFIG_TOUCHSCREEN_FOCAL_FT8719_E7T) += focaltech_test_detail_threshold.o
obj-$(CONFIG_TOUCHSCREEN_FOCAL_FT8719_E7T) += supported_ic/

