#
# Makefile for the focaltech touchscreen drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_TOUCHSCREEN_FOCAL_FT8719_D2T) += focaltech_core.o
obj-$(CONFIG_TOUCHSCREEN_FOCAL_FT8719_D2T) += focaltech_ex_fun.o
obj-$(CONFIG_TOUCHSCREEN_FOCAL_FT8719_D2T) += focaltech_ex_mode.o
obj-$(CONFIG_TOUCHSCREEN_FOCAL_FT8719_D2T) += focaltech_flash.o
obj-$(CONFIG_TOUCHSCREEN_FOCAL_FT8719_D2T) += focaltech_gesture.o
obj-$(CONFIG_TOUCHSCREEN_FOCAL_FT8719_D2T) += focaltech_esdcheck.o
obj-$(CONFIG_TOUCHSCREEN_FOCAL_FT8719_D2T) += focaltech_i2c.o
obj-$(CONFIG_TOUCHSCREEN_FOCAL_FT8719_D2T) += focaltech_point_report_check.o
obj-$(CONFIG_TOUCHSCREEN_FOCAL_FT8719_D2T) += focaltech_flash/
obj-$(CONFIG_TOUCHSCREEN_FOCAL_FT8719_D2T) += focaltech_test/
